version: '3.4'
services:
  db:
    image: ericksantos97/mysql-spring-restful-api
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: rest_with_spring_boot
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  spring-restful-api:
    image: ericksantos97/spring-restful-api
    restart: always
    build: ./spring-restful-api
    working_dir: /spring-restful-api
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./spring-restful-api:/spring-restful-api
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge